name: mlops-example
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v5
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.MY_PAT }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
          
          # Create CML report
          cat metrics.txt >> report.md
          echo "## Model Metrics" > report.md

          cml comment create report.md
